name: Release

on: 
  push:
    tags:
      - 'v*' # 例: v1.0.0, v1.0.1など

jobs:
  build:
    permissions:
      contents: write # リリースを作成するための権限
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.14.0'

    - name: Install dependencies
      run: npm i

    - name: Build and release Electron app
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run dist 